export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const TOGGLE_TODO_EDITING = 'TOGGLE_TODO_EDITING';
export const TOGGLE_TODO_COMPLETED = 'TOGGLE_TODO_COMPLETED';
